version: '3.4'

services:
  analytics:
    image: ${DOCKER_REGISTRY-}analytics
    build:
      context: .
      dockerfile: Analytics/Dockerfile
    ports:
      - "3032:3032"
    links:
      - redis_db
      - mongodb

  ckobank:
    image: ${DOCKER_REGISTRY-}ckobank
    build:
      context: .
      dockerfile: CKOBank/Dockerfile
    ports: 
      - "3031:3031"


  fulfilment:
    image: ${DOCKER_REGISTRY-}fulfilment
    build:
      context: .
      dockerfile: Fulfilment/Dockerfile
    ports:
      - "3030:3030"
    links:
      - redis_db
      - mongodb

  
  redis_db:
    image: redis:3.2.8
    ports: 
      - "6379:6379"
      
  mongodb:
    image: mongo:latest
    ports: 
      - "27017:27017"